/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WhFrameworkAPI
 * OpenAPI spec version: v1
 */
export interface AgGridColumn {
  /** @nullable */
  Id?: string | null;
  /** @nullable */
  DisplayName?: string | null;
  /** @nullable */
  IsPivot?: boolean | null;
}

/**
 * @nullable
 */
export type AgGridDataTableLazyLoadResult1GroupTotals = {[key: string]: unknown} | null;

/**
 * @nullable
 */
export type AgGridDataTableLazyLoadResult1AdditionalData = unknown | null;

export interface AgGridDataTableLazyLoadResult1 {
  /** @nullable */
  rows: T[] | null;
  totalRecords?: number;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  queryTime?: string | null;
  /** @nullable */
  executionTime?: string | null;
  /** @nullable */
  groupTotals?: AgGridDataTableLazyLoadResult1GroupTotals;
  /** @nullable */
  additionalData?: AgGridDataTableLazyLoadResult1AdditionalData;
}

export interface AgGridFieldChangeMap {
  /** @nullable */
  OriginalFieldName: string | null;
  /** @nullable */
  NewFieldName?: string | null;
  /** @nullable */
  AgGridValueChangeMap?: AgGridValueChangeMap[] | null;
  /** @nullable */
  StripString?: string[] | null;
}

export interface AgGridFilterModel {
  /** @nullable */
  FilterType?: string | null;
  /** @nullable */
  Type?: string | null;
  /** @nullable */
  Filter?: string | null;
  /** @nullable */
  FilterTo?: string | null;
  /** @nullable */
  Values?: string[] | null;
  /** @nullable */
  Operator?: string | null;
  /** @nullable */
  Conditions?: AgGridFilterModel[] | null;
}

/**
 * @nullable
 */
export type AgGridRequestFilterModel = {[key: string]: AgGridFilterModel} | null;

/**
 * @nullable
 */
export type AgGridRequestExtraParams = unknown | null;

/**
 * @nullable
 */
export type AgGridRequestContext = {[key: string]: string} | null;

export interface AgGridRequest {
  StartRow?: number;
  EndRow?: number;
  /** @nullable */
  SortModel?: AgGridSortModel[] | null;
  /** @nullable */
  FilterModel?: AgGridRequestFilterModel;
  /** @nullable */
  RowGroupCols?: AgGridColumn[] | null;
  /** @nullable */
  ValueCols?: AgGridColumn[] | null;
  /** @nullable */
  PivotCols?: AgGridColumn[] | null;
  /** @nullable */
  PivotMode?: boolean | null;
  /** @nullable */
  OnlyOneRowId?: string | null;
  /** @nullable */
  ExtraParams?: AgGridRequestExtraParams;
  /** @nullable */
  PrimaryKeyFieldName?: string | null;
  /** @nullable */
  Context?: AgGridRequestContext;
}

export interface AgGridSortModel {
  /** @nullable */
  ColId: string | null;
  /** @nullable */
  Sort?: string | null;
}

export interface AgGridValueChangeMap {
  /** @nullable */
  OriginalValue: string | null;
  /** @nullable */
  NewValue: string | null;
}

export interface Attachments {
  AttachmentId?: string;
  /** @nullable */
  FileName: string | null;
  /** @nullable */
  FileExtension?: string | null;
  /** @nullable */
  MimeType?: string | null;
  /** @nullable */
  FileSize?: number | null;
  /** @nullable */
  FilePath: string | null;
  /** @nullable */
  UploadUser: string | null;
  /** @nullable */
  UpdateDatetime?: string | null;
  /** @nullable */
  Description?: string | null;
}

export interface Base {
  /** @nullable */
  CreationTime?: string | null;
  /** @nullable */
  UpdateTime?: string | null;
  CreateUserId?: number;
  /** @nullable */
  CreateUserName?: string | null;
  UpdateUserId?: number;
  /** @nullable */
  UpdateUserName?: string | null;
  /** @nullable */
  CreationPerson?: string | null;
  /** @nullable */
  CreationPersonName?: string | null;
  /** @nullable */
  UpdatePerson?: string | null;
  /** @nullable */
  UpdatePersonName?: string | null;
}

export interface Company {
  CompanyId?: string;
  /** @nullable */
  DeptId?: string | null;
  /** @nullable */
  TaxId?: string | null;
  /** @nullable */
  CompanyName?: string | null;
  IsActive?: boolean;
  CreationTime?: string;
  UpdateTime?: string;
}

export interface CompanyServiceIntegration {
  Id?: string;
  CompanyId?: string;
  /** @nullable */
  ServiceType?: string | null;
  /** @nullable */
  EndpointName?: string | null;
  /** @nullable */
  EnvType?: string | null;
  /** @nullable */
  ApiBaseUrl?: string | null;
  IsActive?: boolean;
  CreationTime?: string;
  UpdateTime?: string;
}

export interface CompanyServiceIntegrationDto {
  Id?: string;
  CompanyId?: string;
  /** @nullable */
  ServiceType?: string | null;
  /** @nullable */
  EndpointName?: string | null;
  /** @nullable */
  EnvType?: string | null;
  /** @nullable */
  ApiBaseUrl?: string | null;
  IsActive?: boolean;
  CreationTime?: string;
  UpdateTime?: string;
  /** @nullable */
  Params?: CompanyServiceParam[] | null;
}

export interface CompanyServiceParam {
  Id?: string;
  IntegrationId?: string;
  /** @nullable */
  ParamKey?: string | null;
  /** @nullable */
  ParamValue?: string | null;
  /** @nullable */
  Memo?: string | null;
  CreationTime?: string;
  UpdateTime?: string;
}

export interface DepartmentManagers {
  DepartmentId: number;
  UserId: number;
  ManagerOrder: number;
}

export interface Departments {
  DepartmentId: number;
  /** @nullable */
  DepartmentName: string | null;
  /** @nullable */
  DepartmentDescription: string | null;
  ParentDepartmentId: number;
  /** @nullable */
  ParentDepartmentName?: string | null;
  /** @nullable */
  DepartmentLevel: string | null;
  CreationTime: string;
  UpdateTime: string;
}

export interface DepartmentsDTO {
  DepartmentId: number;
  /** @nullable */
  DepartmentName: string | null;
  /** @nullable */
  DepartmentDescription: string | null;
  ParentDepartmentId: number;
  /** @nullable */
  ParentDepartmentName?: string | null;
  /** @nullable */
  DepartmentLevel: string | null;
  CreationTime: string;
  UpdateTime: string;
  /** @nullable */
  Managers?: number[] | null;
}

export interface ErrorViewModel {
  /** @nullable */
  RequestId?: string | null;
  readonly ShowRequestId?: boolean;
}

export interface FileDownloadDto {
  /** @nullable */
  FileStream: Blob | null;
  /** @nullable */
  ContentType: string | null;
  /** @nullable */
  FileName: string | null;
}

export interface GroupPermissions {
  GroupId: number;
  PermissionId: number;
}

export interface Groups {
  GroupId: number;
  /** @nullable */
  GroupName: string | null;
  /** @nullable */
  GroupDescription?: string | null;
  /** @nullable */
  PermissionGroupType: string | null;
  IsAdmin: boolean;
  IsSystemReserved: boolean;
  CreationTime: string;
}

export interface GroupsWithPermissionsList {
  GroupId: number;
  /** @nullable */
  GroupName: string | null;
  /** @nullable */
  GroupDescription?: string | null;
  /** @nullable */
  PermissionGroupType: string | null;
  IsAdmin: boolean;
  IsSystemReserved: boolean;
  CreationTime: string;
  /** @nullable */
  GroupPermissions?: number[] | null;
}

export interface ImportReconciliationParameters {
  /** @nullable */
  PersonId?: string | null;
  /** @nullable */
  Data?: LogisticsReconciliationItem[] | null;
  /** @nullable */
  OriginalFileContent?: string | null;
}

/**
 * @nullable
 */
export type JsonResponseData = unknown | null;

export interface JsonResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: JsonResponseData;
  /** @nullable */
  timestamp?: string | null;
}

export interface LineBindRequest {
  /** @nullable */
  Username: string | null;
  /** @nullable */
  Password: string | null;
  /** @nullable */
  LineIdToken: string | null;
  /** @nullable */
  CaptchaId?: string | null;
  /** @nullable */
  CaptchaAnswer?: string | null;
}

export interface LineVerifyIdTokenResponse {
  /** @nullable */
  Iss?: string | null;
  /** @nullable */
  Sub?: string | null;
  /** @nullable */
  Aud?: string | null;
  Exp?: number;
  /** @nullable */
  Name?: string | null;
  /** @nullable */
  Picture?: string | null;
  /** @nullable */
  Email?: string | null;
}

export interface LoginRequest {
  /** @nullable */
  Username?: string | null;
  /** @nullable */
  Password?: string | null;
  /** @nullable */
  CaptchaId?: string | null;
  /** @nullable */
  CaptchaAnswer?: string | null;
}

export interface LogisticsReconciliationItem {
  /** @nullable */
  ShipmentDate?: string | null;
  /** @nullable */
  TrackingNumber?: string | null;
  /** @nullable */
  OrderNo?: string | null;
  CodAmount?: number;
  Fee?: number;
  /** @nullable */
  Remark?: string | null;
}

export interface Logs {
  Id: string;
  /** @nullable */
  LogType?: string | null;
  /** @nullable */
  ActionType?: string | null;
  /** @nullable */
  ModuleName?: string | null;
  /** @nullable */
  LogData: string | null;
  Timestamp: string;
  /** @nullable */
  Username: string | null;
}

export interface Notifications {
  NotificationId: string;
  /** @nullable */
  UserId?: number | null;
  /** @nullable */
  NotificationMessageContent: string | null;
  /** @nullable */
  NotificationErrorMessageContent?: string | null;
  NotificationPriority: number;
  /** @nullable */
  NotificationType: string | null;
  /** @nullable */
  NotificationLink?: string | null;
  IsLinkNewWindow?: boolean;
  IsInternalLink?: boolean;
  IsBlob?: boolean;
  ProductionPercentage: number;
  /** @nullable */
  ReadTime?: string | null;
  CreationTime: string;
  /** @nullable */
  NotificationExpiresTime?: string | null;
}

export interface Parameter {
  ParameterId: string;
  /** @nullable */
  Category: string | null;
  /** @nullable */
  Code: string | null;
  /** @nullable */
  Description: string | null;
  /** @nullable */
  Memo?: string | null;
  IsSystemReserved: boolean;
}

export interface Permissions {
  PermissionId: number;
  /** @nullable */
  ModuleName: string | null;
  /** @nullable */
  PermissionModuleSubType: string | null;
  /** @nullable */
  PermissionDescription?: string | null;
  IsPublic: boolean;
  CanRead: boolean;
  CanReadAll: boolean;
  CanCreate: boolean;
  CanUpdate: boolean;
  CanDelete: boolean;
  CanManage: boolean;
  IsSystemReserved: boolean;
  CreationTime: string;
}

export interface RefreshTokenRequest {
  /** @nullable */
  RefreshToken: string | null;
}

export interface ReportOkrQueryParameters {
  /** @nullable */
  ReportType?: string | null;
  StartDate?: number;
  EndDate?: number;
  /** @nullable */
  ComparisonYear1?: number | null;
  /** @nullable */
  ComparisonYear2?: number | null;
}

export interface ReportOthersQueryParameters {
  CompanyId?: string;
  /** @nullable */
  ReportType?: string | null;
  StartDate?: number;
  EndDate?: number;
}

export interface RolePermissions {
  RoleId: number;
  PermissionId: number;
}

export interface Roles {
  RoleId: number;
  /** @nullable */
  RoleName: string | null;
  /** @nullable */
  RoleDescription?: string | null;
  IsAdmin: boolean;
  IsSystemReserved: boolean;
  CreationTime: string;
}

export interface RolesWithPermissionsList {
  RoleId: number;
  /** @nullable */
  RoleName: string | null;
  /** @nullable */
  RoleDescription?: string | null;
  IsAdmin: boolean;
  IsSystemReserved: boolean;
  CreationTime: string;
  /** @nullable */
  RolePermissions?: number[] | null;
}

export interface SalePerformanceDto {
  /** @nullable */
  Schedule?: string | null;
  /** @nullable */
  OrderDate?: number | null;
  /** @nullable */
  OrderNo?: string | null;
  /** @nullable */
  CustomerID?: string | null;
  /** @nullable */
  FullName?: string | null;
  /** @nullable */
  PersonName?: string | null;
  /** @nullable */
  Sale?: number | null;
  /** @nullable */
  OrderMoney?: number | null;
  /** @nullable */
  AddMoney?: number | null;
  /** @nullable */
  DepositPercent?: string | null;
  /** @nullable */
  DepositLack?: number | null;
  /** @nullable */
  Deposit70Percent?: number | null;
  /** @nullable */
  Deposit30Percent?: number | null;
  /** @nullable */
  ActShipmentDate?: string | null;
  /** @nullable */
  ExpectedDeliveryDate?: string | null;
  /** @nullable */
  DeliveryDriver?: string | null;
  /** @nullable */
  UserDescription?: string | null;
  /** @nullable */
  SalePercent?: string | null;
  /** @nullable */
  IsExistSale?: string | null;
}

export interface SelectListItemDto {
  /** @nullable */
  Label: string | null;
  /** @nullable */
  Value: string | null;
}

export interface Sequence {
  SequenceId: number;
  SequenceRuleId: number;
  /** @nullable */
  GroupingValue: string | null;
  CurrentNumber: number;
  UpdateTime?: string;
}

export interface SequenceRule {
  SequenceRuleId: number;
  /** @nullable */
  RuleName: string | null;
  /** @nullable */
  Description?: string | null;
  /** @nullable */
  EncodingPattern: string | null;
  /** @nullable */
  SequenceGroupingPattern: string | null;
  /** @nullable */
  FixedCode1?: string | null;
  /** @nullable */
  FixedCode2?: string | null;
  /** @nullable */
  FixedCode3?: string | null;
  SequenceLength: number;
}

export interface ServiceType { [key: string]: unknown }

export interface T { [key: string]: unknown }

export interface T8UserDto {
  UserId: number;
  /** @nullable */
  Username: string | null;
  /** @nullable */
  Password: string | null;
  /** @nullable */
  UserDescription: string | null;
  DepartmentId?: number;
  /** @nullable */
  UserEmail?: string | null;
  /** @nullable */
  LineUserId?: string | null;
  CreationTime?: string;
  UpdateTime?: string;
  /** @nullable */
  Token?: string | null;
  /** @nullable */
  PersonId?: string | null;
  /** @nullable */
  PersonName?: string | null;
}

export interface UserChangePasswordDTO {
  /** @nullable */
  NewPassword: string | null;
  /** @nullable */
  ConfirmPassword: string | null;
}

export interface UserClaims {
  UserId: number;
  /** @nullable */
  Username: string | null;
  /** @nullable */
  UserDescription?: string | null;
  /** @nullable */
  Permission?: Permissions[] | null;
  /** @nullable */
  PersonId?: string | null;
  /** @nullable */
  PersonName?: string | null;
}

export interface UserGroups {
  UserId: number;
  GroupId: number;
}

export interface UserRefreshToken {
  TokenId?: string;
  UserId?: number;
  /** @nullable */
  RefreshToken?: string | null;
  CreationTime?: string;
  ExpiryTime?: string;
  IsRevoked?: boolean;
  /** @nullable */
  RevokedReason?: string | null;
  /** @nullable */
  DeviceInfo?: string | null;
  /** @nullable */
  IpAddress?: string | null;
}

export interface UserRoles {
  UserId: number;
  RoleId: number;
}

export interface UserSessionData {
  UserId: number;
  /** @nullable */
  Username: string | null;
  /** @nullable */
  UserDescription: string | null;
  DepartmentId?: number;
  /** @nullable */
  UserEmail?: string | null;
  /** @nullable */
  LineUserId?: string | null;
  /** @nullable */
  Token?: string | null;
  /** @nullable */
  Permissions?: Permissions[] | null;
  /** @nullable */
  RefreshToken?: string | null;
  /** @nullable */
  RefreshTokenExpiry?: string | null;
  /** @nullable */
  PersonId?: string | null;
  /** @nullable */
  PersonName?: string | null;
}

export interface Users {
  UserId: number;
  /** @nullable */
  Username: string | null;
  /** @nullable */
  Password: string | null;
  /** @nullable */
  UserDescription: string | null;
  DepartmentId?: number;
  /** @nullable */
  UserEmail?: string | null;
  /** @nullable */
  LineUserId?: string | null;
  CreationTime?: string;
  UpdateTime?: string;
  /** @nullable */
  Token?: string | null;
}

export interface UsersDTO {
  UserId: number;
  /** @nullable */
  Username: string | null;
  /** @nullable */
  Password: string | null;
  /** @nullable */
  UserDescription: string | null;
  DepartmentId?: number;
  /** @nullable */
  UserEmail?: string | null;
  /** @nullable */
  LineUserId?: string | null;
  CreationTime?: string;
  UpdateTime?: string;
  /** @nullable */
  Token?: string | null;
  /** @nullable */
  Groups?: number[] | null;
  /** @nullable */
  Roles?: number[] | null;
}

export type PostApiAttachmentUploadParams = {
uploadPersonId?: string;
extensionFilePath?: string;
description?: string;
};

export type PostApiAttachmentUploadBody = {
  file?: Blob;
};

export type GetApiWebGenerateCaptchaParams = {
isDarkTheme?: boolean;
};

export type GetApiWebGetUserIsDarkThemeParams = {
UserId?: number;
};

export type GetApiWebSetUserIsDarkThemeParams = {
UserId?: number;
IsDarkTheme?: boolean;
};

export type GetApiWebMarkNotificationReadParams = {
NotificationId?: string;
};

export type GetApiWebFetchDepartmentRecordParams = {
DepartmentId?: number;
};

export type GetApiWebFetchDepartmentManagersRecordParams = {
DepartmentId?: number;
};

export type GetApiWebDepartmentsDelParams = {
DepartmentId?: number;
};

export type GetApiLineCheckLineBindParams = {
LineIdToken?: string;
};

export type GetApiLineLiffRouteLoginParams = {
LineIdToken?: string;
};

export type GetApiWebFetchParameterRecordParams = {
ParameterId?: string;
};

export type GetApiWebParameterDelParams = {
ParameterId?: string;
};

export type PostApiWebGetParametersParams = {
category?: string;
};

export type GetApiWebGetPrefixParametersParams = {
CategoryPrefix?: string;
};

export type GetApiWebFetchRolesRecordParams = {
RoleId?: number;
};

export type GetApiWebFetchRolePermissionsParams = {
RoleId?: number;
};

export type GetApiWebRolesDelParams = {
RoleId?: number;
};

export type GetApiWebFetchGroupsRecordParams = {
GroupId?: number;
};

export type GetApiWebFetchGroupPermissionsParams = {
GroupId?: number;
};

export type GetApiWebGroupsDelParams = {
GroupId?: number;
};

export type GetApiWebFetchPermissionsRecordParams = {
PermissionId?: number;
};

export type GetApiWebPermissionsDelParams = {
PermissionId?: number;
};

export type GetApiWebFetchCompanyServiceIntegrationParams = {
integrationId?: string;
};

export type GetApiWebCompanyServiceIntegrationDelParams = {
integrationId?: string;
};

export type GetApiWebFetchCompanyServiceParamsParams = {
integrationId?: string;
};

export type GetApiWebFetchUsersRecordParams = {
UserId?: number;
};

export type GetApiWebFetchUserGroupsByUserIdParams = {
UserId?: number;
};

export type GetApiWebFetchUserRolesByUserIdParams = {
UserId?: number;
};

export type GetApiWebUsersDelParams = {
UserId?: number;
};

